- name: Dart and Flutter Package Publisher
  # You may pin to the exact commit or the version.
  # uses: k-paxian/dart-package-publisher@cf42c35a2a6f3e2e4cd4a6e60450c6de75f4ba67
  uses: k-paxian/dart-package-publisher@v1.4
  with:
    # (Required) Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_ACCESS_TOKEN
    accessToken: 
    # (Required) Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_REFRESH_TOKEN
    refreshToken: 
    # (Optional) Overrides accessToken and refreshToken. Whole content of ~/.pub-cache/credentials.json. Use secrets.CREDENTIAL_JSON
    credentialJson: # optional
    # (Optional) Path to your package root in your repository
    relativePath: # optional, default is 
    # (Optional) Perform dry run only, no real publishing
    dryRunOnly: # optional
    # (Optional) Skip unit tests run
    skipTests: # optional
    # (Optional) Suppress using `build_runner` for unit tests run
    suppressBuildRunner: # optional
    # (Optional) Format code of project to get better score in pub.dev
    format: # optional
    # (Optional) Force publishing even if pub tool throws warnings, hints, etc
    force: # optional
    # (Optional) Flutter package type
    flutter: # optional
